/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForRepresentativesRouteImport } from './routes/for-representatives'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as RequestCallRouteImport } from './routes/request-call'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WallRouteImport } from './routes/wall'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForRepresentativesRoute = ForRepresentativesRouteImport.update({
  id: '/for-representatives',
  path: '/for-representatives',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestCallRoute = RequestCallRouteImport.update({
  id: '/request-call',
  path: '/request-call',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WallRoute = WallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/for-representatives': typeof ForRepresentativesRoute
  '/get-involved': typeof GetInvolvedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/request-call': typeof RequestCallRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wall': typeof WallRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/for-representatives': typeof ForRepresentativesRoute
  '/get-involved': typeof GetInvolvedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/request-call': typeof RequestCallRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wall': typeof WallRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/for-representatives': typeof ForRepresentativesRoute
  '/get-involved': typeof GetInvolvedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/request-call': typeof RequestCallRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wall': typeof WallRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/for-representatives'
    | '/get-involved'
    | '/how-it-works'
    | '/request-call'
    | '/sitemap.xml'
    | '/wall'
    | '/account'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/for-representatives'
    | '/get-involved'
    | '/how-it-works'
    | '/request-call'
    | '/sitemap.xml'
    | '/wall'
    | '/account'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/for-representatives'
    | '/get-involved'
    | '/how-it-works'
    | '/request-call'
    | '/sitemap.xml'
    | '/wall'
    | '/_authenticated/account'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ForRepresentativesRoute: typeof ForRepresentativesRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  RequestCallRoute: typeof RequestCallRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WallRoute: typeof WallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-representatives': {
      id: '/for-representatives'
      path: '/for-representatives'
      fullPath: '/for-representatives'
      preLoaderRoute: typeof ForRepresentativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-call': {
      id: '/request-call'
      path: '/request-call'
      fullPath: '/request-call'
      preLoaderRoute: typeof RequestCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wall': {
      id: '/wall'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof WallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ForRepresentativesRoute: ForRepresentativesRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  HowItWorksRoute: HowItWorksRoute,
  RequestCallRoute: RequestCallRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WallRoute: WallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
